local constant = {
	damage = nil,
	speed = nil,
	ammo = {
		current_ammo = nil,
		mag_size = nil,
		reserve_ammo = nil,
		max_reserve_ammo = nil,
	},
	piersing = {
		strength_loss = nil,
		amount = nil,
	},
	crit_chance = nil,
	accuracy = nil,
	reload_time = nil,
	draw_time = nil,
	mode = nil,
	type = nil,
	pellets = nil,
	multiplier = {
		head = nil,
		body = nil,
		crit = nil,
	},
}

return constant
